# Site settings
title: Indiaviewpoint.in
email: contact@indiaviewpoint.in
description: > # this means to ignore newlines until indiaviewpoint.in is a blog website that publishes articles related to science, technology, cyberspace and social science.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://indiaviewpoint.github.io" # the base hostname & protocol for your site
twitter_username: indviewpoint
Linkedln_username: indiaviewpoint
instagram_username: indiaviewpoint
facebook_username: indiaviewpoint


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title/
jobtitle: "Research/Science blog website"
excerpt_separator: "<!--more-->"

# SEO stuff
google_author: 
google_site_verification: 
bing_webmastertools_id:

plugins_dir:
  - jekyll-sitemap

exclude: ['*.Rmd']
